[package]
name = "pallet-token-gateway"
version = "16.2.0"
edition = "2021"
description = "A substrate implementation of the token gateway protocol"
authors = ["Polytope Labs <hello@polytope.technology>"]
license = "Apache-2.0"
repository = "https://github.com/polytope-labs/hyperbridge"
homepage = "https://docs.hyperbridge.network/developers/polkadot/token-gateway"
documentation = "https://docs.rs/pallet-token-gateway"
keywords = [
    "substrate",
    "polkadot-sdk",
    "ISMP",
    "interoperability",
    "pallet-assets",
]
readme = "README.md"

[dependencies]
primitive-types = { workspace = true }
log = { workspace = true }
codec = { workspace = true }
scale-info = { workspace = true }
anyhow = { workspace = true }
alloy-primitives = { workspace = true }
alloy-sol-macro = { workspace = true }
alloy-sol-types = { workspace = true }

ismp = { workspace = true }
pallet-ismp = { workspace = true }
token-gateway-primitives = { workspace = true }
pallet-hyperbridge = { workspace = true }

[dependencies.polkadot-sdk]
workspace = true
features = ["frame-support", "frame-system", "sp-runtime", "sp-core", "sp-io"]

[features]
default = ["std"]
std = [
    "polkadot-sdk/std",
    "primitive-types/std",
    "ismp/std",
    "pallet-ismp/std",
    "log/std",
    "scale-info/std",
    "anyhow/std",
    "alloy-primitives/std",
    "pallet-hyperbridge/std",
    "token-gateway-primitives/std",
]
runtime-benchmarks = [
    "polkadot-sdk/frame-benchmarking",
    "polkadot-sdk/runtime-benchmarks",
]
try-runtime = ["polkadot-sdk/try-runtime"]
