[package]
name = "hydration-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = {workspace = true}
tracing = {workspace = true}
sp-runtime = {workspace = true}
sp-core = {workspace = true}
sp-api = {workspace = true}
sc-client-api = {workspace = true}
pallet-ice = {workspace = true, default-features = false}
primitives = {workspace = true}
clarabel = {workspace = true}



