[package]
name = "pallet-evm-accounts-rpc-runtime-api"
version = "1.0.1"
authors = ['GalacticCouncil']
edition = "2021"
license = "Apache-2.0"
homepage = 'https://github.com/galacticcouncil/hydradx-node'
repository = 'https://github.com/galacticcouncil/hydradx-node'
description = "RPC runtime API for EVM accounts pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
sp-api = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-api/std",
]
