[package]
name = "pallet-intent"
version = "1.0.0"
authors = ['GalacticCouncil']
edition = "2021"
license = "Apache-2.0"
homepage = 'https://github.com/galacticcouncil/hydration-node'
repository = 'https://github.com/galacticcouncil/hydration-node'
description = "Hydration Intent pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
scale-info = { workspace = true}
codec = { workspace = true }
log = { workspace = true }
serde = {workspace = true}

hydradx-traits = { workspace = true }
hydra-dx-math = {workspace = true}
orml-traits = { workspace = true }

sp-runtime = { workspace = true }
sp-std = { workspace = true }
sp-api = { workspace = true }
sp-runtime-interface = {workspace = true}
sp-externalities = {workspace = true}

frame-support = { workspace = true }
frame-system = { workspace = true }

# Optional imports for benchmarking
frame-benchmarking = { workspace = true, optional = true }
sp-core = { workspace = true}
sp-io = { workspace = true}

[dev-dependencies]
pretty_assertions = "1.2.1"
orml-tokens = {workspace = true}
pallet-balances = { workspace = true}
pallet-currencies = { workspace = true}
orml-traits = { workspace = true}

[features]
default = [ "std" ]
std = [
    "codec/std",
    "frame-benchmarking/std",
    "frame-support/std",
    "frame-system/std",
    "hydra-dx-math/std",
    "hydradx-traits/std",
    "log/std",
    "orml-tokens/std",
    "orml-traits/std",
    "pallet-balances/std",
    "pallet-currencies/std",
    "scale-info/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-api/std",
    "sp-runtime-interface/std",
    "sp-externalities/std",
]
runtime-benchmarks = [ "frame-benchmarking/runtime-benchmarks" ]
try-runtime = [ "frame-support/try-runtime" ]
