[package]
name = "ice-solver"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
pallet-ice = { workspace = true}
sp-std = {workspace = true}
sp-runtime = {workspace = true}
hydradx-traits = {workspace = true}

clarabel = {workspace = true}

[dev-dependencies]
rand = { version = "0.8.5", default-features = false }
serde_json = {workspace = true}

[features]
default = [ "std" ]
std = [
	"hydradx-traits/std",
	"pallet-ice/std",
	"sp-runtime/std",
	"sp-std/std",
]
