[package]
name = "ice-solver"
version = "0.1.0"
edition = "2021"

[dependencies]
hydra-dx-math = { workspace =  true}
pallet-ice = { workspace = true}
sp-std = {workspace = true}
sp-io = {workspace = true}
sp-runtime = {workspace = true}
orml-traits = {workspace = true}
hydradx-traits = {workspace = true}

clarabel = { path ="../../../../clarabel", version = "0" , default-features = false }

[dev-dependencies]
rand = "0.8.5"

[features]
default = ["std"]
std = [
    "hydra-dx-math/std",
    "pallet-ice/std",
    "sp-std/std",
    "sp-io/std",
    "sp-runtime/std",
    "orml-traits/std",
    "hydradx-traits/std",
    "clarabel/wasm"
]