= Contributing

`HydraDX` is an [OPEN Open Source Project](http://openopensource.org/)

-----------------------------------------

== What?

Individuals making significant and valuable contributions are given
commit-access to the project to contribute as they see fit. This project
is more like an open wiki than a standard guarded open source project.

== Rules

There are a few basic ground-rules for contributors (including the maintainer(s) of the project):

. **No `--force` pushes** or modifying the master branch history in any way.
. **Non-master branches** ought to be used for ongoing work.
. **All modifications** ought to be subject to an **internal pull-request** to solicit feedback from other contributors.
. **Titles of Pull-requests** should follow [Semantic Pull Requests](https://github.com/zeke/semantic-pull-requests/blob/master/README.md) guidelines.
. Contributors should attempt to adhere to the prevailing code-style.

== Releases

Declaring formal releases remains the prerogative of the project maintainers.

== Changes to this arrangement

This is an experiment and feedback is welcome! This document may also be
subject to pull-requests or changes by contributors where you believe
you have something valuable to add or change.

These contributing guidelines are modified from the [OPEN Open Source Project](http://openopensource.org/) guidelines.