name: Semantic

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test_update:
    name: Test Update
    runs-on: ubuntu-latest
    steps:
      - name: Echo test message
        run: echo "This is a test update"
